context:
  version: "0.10.0"

package:
  name: asm-lsp
  version: ${{ version }}

source:
  url: https://github.com/bergercookie/asm-lsp/archive/v${{ version }}.tar.gz
  sha256: 4755848aa7d88856be7e40d0930990b95b46c4593a53db3809d3ba7214d9d16d

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openssl

tests:
  - script:
    - asm-lsp --help

about:
  license: BSD-2-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Language server for NASM/GAS/GO Assembly
  homepage: https://github.com/bergercookie/asm-lsp
  repository: https://github.com/bergercookie/asm-lsp

extra:
  recipe-maintainers:
    - danielnachun
