context:
  version: 0.9.0

package:
  name: asm-lsp
  version: ${{ version }}

source:
  url: https://github.com/bergercookie/asm-lsp/archive/v${{ version }}.tar.gz
  sha256: 863bdc5aad7039f7f355e09a2a759adbef6ea40b9efb3085f7bee4a382d79e11

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openssl

tests:
  - requirements:
      run:
        - if: win
          then: m2-grep
    script:
      - asm-lsp 2>&1 | grep -q "Starting asm_lsp..."

about:
  license: BSD-2-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Language server for NASM/GAS/GO Assembly
  homepage: https://github.com/bergercookie/asm-lsp
  repository: https://github.com/bergercookie/asm-lsp

extra:
  recipe-maintainers:
    - danielnachun
